/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_raymond_jniexample_Testjni */

#ifndef _Included_com_raymond_jniexample_Testjni
#define _Included_com_raymond_jniexample_Testjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_raymond_jniexample_Testjni
 * Method:    init
 * Signature: ()Z
 */JNIEXPORT jboolean JNICALL Java_com_raymond_jniexample_Testjni_init(JNIEnv *,
		jobject);
/*
 * Class:     com_raymond_jniexample_Testjni
 * Method:    add
 * Signature: (II)I
 */JNIEXPORT jint JNICALL Java_com_raymond_jniexample_Testjni_add(JNIEnv *,
		jobject, jint, jint);

/*
 * Class:     com_raymond_jniexample_Testjni
 * Method:    destroy
 * Signature: ()V
 */JNIEXPORT void JNICALL Java_com_raymond_jniexample_Testjni_destroy(JNIEnv *,
		jobject);

#ifdef __cplusplus
}
#endif
#endif
